import { Order, OrderItem, OrderStatus } from '../features/orders/types';
import { MenuItem, MenuCategory } from '../features/menu/types';
import { SalesSummary, PopularItem } from '../features/analytics/types';
import { RestaurantOwner } from '../features/auth/types';

export const mockRestaurantOwner: RestaurantOwner = {
  id: 'usr_123',
  tenantId: 'tenant_siam_001',
  fullName: 'John Smith',
  email: 'john@siamauthentic.com',
  phone: '0412345678',
  role: 'owner',
  primaryAddress: '123 Restaurant St, Sydney NSW 2000',
};

export const mockOrders: Order[] = [
  {
    id: 'ord_1001',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_456',
    customerName: 'Sarah Chen',
    customerPhone: '0412345678',
    items: [
      { id: 'item_1', name: 'Pad Thai', quantity: 2, price: 15.50, modifiers: ['Extra Sauce'] },
      { id: 'item_5', name: 'Spring Rolls', quantity: 1, price: 10.00 },
    ],
    subtotal: 41.00,
    deliveryFee: 5.00,
    loyaltyDiscount: 0,
    total: 46.00,
    status: 'Pending',
    fulfillmentMethod: 'delivery',
    deliveryAddress: '45 Harbour St, Sydney NSW 2000',
    notes: 'No spicy, extra sauce please',
    createdAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_1002',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_457',
    customerName: 'Mike Johnson',
    customerPhone: '0423456789',
    items: [
      { id: 'item_10', name: 'Tom Yum Soup', quantity: 1, price: 16.00 },
      { id: 'item_11', name: 'Green Curry', quantity: 1, price: 18.00 },
    ],
    subtotal: 34.00,
    deliveryFee: 0,
    loyaltyDiscount: 0,
    total: 34.00,
    status: 'Accepted',
    fulfillmentMethod: 'pickup',
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_1003',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_458',
    customerName: 'Emma Wilson',
    customerPhone: '0434567890',
    items: [
      { id: 'item_12', name: 'Massaman Curry', quantity: 2, price: 19.00 },
      { id: 'item_8', name: 'Mango Sticky Rice', quantity: 2, price: 9.00 },
    ],
    subtotal: 56.00,
    deliveryFee: 5.00,
    loyaltyDiscount: 5.00,
    total: 56.00,
    status: 'Preparing',
    fulfillmentMethod: 'delivery',
    deliveryAddress: '78 George St, Sydney NSW 2000',
    notes: '',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_1004',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_459',
    customerName: 'David Lee',
    items: [
      { id: 'item_3', name: 'Satay Chicken', quantity: 1, price: 12.00 },
      { id: 'item_7', name: 'Thai Basil Fried Rice', quantity: 1, price: 16.00 },
      { id: 'item_13', name: 'Thai Iced Tea', quantity: 2, price: 5.00 },
    ],
    subtotal: 38.00,
    deliveryFee: 5.00,
    loyaltyDiscount: 0,
    total: 43.00,
    status: 'Ready',
    fulfillmentMethod: 'delivery',
    deliveryAddress: '12 Pitt St, Sydney NSW 2000',
    notes: 'Ring bell twice',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_1005',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_460',
    customerName: 'Lisa Park',
    items: [
      { id: 'item_1', name: 'Pad Thai', quantity: 1, price: 15.50 },
      { id: 'item_15', name: 'Papaya Salad', quantity: 1, price: 14.00 },
    ],
    subtotal: 29.50,
    deliveryFee: 0,
    loyaltyDiscount: 0,
    total: 29.50,
    status: 'Completed',
    fulfillmentMethod: 'pickup',
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_1006',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_461',
    customerName: 'James Brown',
    items: [
      { id: 'item_10', name: 'Tom Yum Soup', quantity: 2, price: 16.00 },
    ],
    subtotal: 32.00,
    deliveryFee: 5.00,
    loyaltyDiscount: 0,
    total: 37.00,
    status: 'Completed',
    fulfillmentMethod: 'delivery',
    deliveryAddress: '56 Kent St, Sydney NSW 2000',
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_1007',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_462',
    customerName: 'Anna White',
    items: [
      { id: 'item_12', name: 'Massaman Curry', quantity: 1, price: 19.00 },
    ],
    subtotal: 19.00,
    deliveryFee: 5.00,
    loyaltyDiscount: 0,
    total: 24.00,
    status: 'Cancelled',
    fulfillmentMethod: 'delivery',
    deliveryAddress: '90 York St, Sydney NSW 2000',
    createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 170 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord_1008',
    tenantId: 'tenant_siam_001',
    customerId: 'cust_463',
    customerName: 'Tom Garcia',
    customerPhone: '0445678901',
    items: [
      { id: 'item_14', name: 'Red Curry', quantity: 1, price: 18.00 },
      { id: 'item_16', name: 'Coconut Ice Cream', quantity: 1, price: 8.00 },
      { id: 'item_13', name: 'Thai Iced Tea', quantity: 1, price: 5.00 },
    ],
    subtotal: 31.00,
    deliveryFee: 5.00,
    loyaltyDiscount: 0,
    total: 36.00,
    status: 'Completed',
    fulfillmentMethod: 'delivery',
    deliveryAddress: '33 Sussex St, Sydney NSW 2000',
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 200 * 60 * 1000).toISOString(),
  },
];

export const mockMenuCategories: MenuCategory[] = [
  {
    id: 'cat_1',
    tenantId: 'tenant_siam_001',
    name: 'Appetizers',
    displayOrder: 1,
    items: [
      {
        id: 'item_1',
        tenantId: 'tenant_siam_001',
        name: 'Spring Rolls',
        description: 'Crispy spring rolls with sweet chili sauce',
        price: 10.00,
        category: 'Appetizers',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 5,
      },
      {
        id: 'item_2',
        tenantId: 'tenant_siam_001',
        name: 'Satay Chicken',
        description: 'Grilled chicken skewers with peanut sauce and cucumber relish',
        price: 12.00,
        category: 'Appetizers',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 8,
      },
      {
        id: 'item_3',
        tenantId: 'tenant_siam_001',
        name: 'Fish Cakes',
        description: 'Traditional Thai fish cakes with green chili and kaffir lime',
        price: 11.00,
        category: 'Appetizers',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 10,
      },
      {
        id: 'item_4',
        tenantId: 'tenant_siam_001',
        name: 'Polygonum Salad',
        description: 'Fresh polygonum leaves with crushed peanut dressing',
        price: 9.00,
        category: 'Appetizers',
        imageUrl: '',
        isAvailable: false,
        preparationTime: 5,
      },
      {
        id: 'item_5',
        tenantId: 'tenant_siam_001',
        name: 'Crispy Duck Rolls',
        description: 'Duck and vegetable rolls with plum sauce',
        price: 13.00,
        category: 'Appetizers',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 7,
      },
    ],
  },
  {
    id: 'cat_2',
    tenantId: 'tenant_siam_001',
    name: 'Soups',
    displayOrder: 2,
    items: [
      {
        id: 'item_10',
        tenantId: 'tenant_siam_001',
        name: 'Tom Yum Soup',
        description: 'Hot and sour soup with shrimp, mushrooms, and lemongrass',
        price: 16.00,
        category: 'Soups',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 10,
      },
      {
        id: 'item_11',
        tenantId: 'tenant_siam_001',
        name: 'Tom Kha Gai',
        description: 'Chicken coconut soup with galangal and lime leaves',
        price: 15.00,
        category: 'Soups',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 12,
      },
      {
        id: 'item_17',
        tenantId: 'tenant_siam_001',
        name: 'Wonton Soup',
        description: 'Clear broth with pork and shrimp wontons',
        price: 12.00,
        category: 'Soups',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 8,
      },
    ],
  },
  {
    id: 'cat_3',
    tenantId: 'tenant_siam_001',
    name: 'Mains',
    displayOrder: 3,
    items: [
      {
        id: 'item_1',
        tenantId: 'tenant_siam_001',
        name: 'Pad Thai',
        description: 'Stir-fried rice noodles with egg, tofu, bean sprouts, and tamarind sauce',
        price: 15.50,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 12,
      },
      {
        id: 'item_8',
        tenantId: 'tenant_siam_001',
        name: 'Thai Basil Fried Rice',
        description: 'Jasmine rice stir-fried with basil, chili, garlic, and choice of protein',
        price: 16.00,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 10,
      },
      {
        id: 'item_12',
        tenantId: 'tenant_siam_001',
        name: 'Massaman Curry',
        description: 'Rich and mild curry with potatoes, peanuts, and beef',
        price: 19.00,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 15,
      },
      {
        id: 'item_11',
        tenantId: 'tenant_siam_001',
        name: 'Green Curry',
        description: 'Aromatic green curry with bamboo shoots, Thai eggplant, and basil',
        price: 18.00,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 14,
      },
      {
        id: 'item_14',
        tenantId: 'tenant_siam_001',
        name: 'Red Curry',
        description: 'Classic red curry with coconut cream, bell peppers, and Thai basil',
        price: 18.00,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 14,
      },
      {
        id: 'item_18',
        tenantId: 'tenant_siam_001',
        name: 'Pad See Ew',
        description: 'Wide rice noodles stir-fried with Chinese broccoli and dark soy sauce',
        price: 15.00,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 12,
      },
      {
        id: 'item_19',
        tenantId: 'tenant_siam_001',
        name: 'Pineapple Fried Rice',
        description: 'Fried rice with pineapple, cashew nuts, raisins, and curry powder',
        price: 16.50,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 11,
      },
      {
        id: 'item_20',
        tenantId: 'tenant_siam_001',
        name: 'Crab Fried Rice',
        description: 'Premium fried rice with fresh crab meat and scallions',
        price: 22.00,
        category: 'Mains',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 13,
      },
    ],
  },
  {
    id: 'cat_4',
    tenantId: 'tenant_siam_001',
    name: 'Salads',
    displayOrder: 4,
    items: [
      {
        id: 'item_15',
        tenantId: 'tenant_siam_001',
        name: 'Papaya Salad',
        description: 'Green papaya salad with chili, lime, peanuts, and dried shrimp',
        price: 14.00,
        category: 'Salads',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 8,
      },
      {
        id: 'item_16',
        tenantId: 'tenant_siam_001',
        name: 'Yum Wan Ten',
        description: 'Spicy glass noodle salad with prawns, tomato, and mint',
        price: 15.00,
        category: 'Salads',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 10,
      },
    ],
  },
  {
    id: 'cat_5',
    tenantId: 'tenant_siam_001',
    name: 'Desserts & Drinks',
    displayOrder: 5,
    items: [
      {
        id: 'item_8',
        tenantId: 'tenant_siam_001',
        name: 'Mango Sticky Rice',
        description: 'Sweet sticky rice with fresh mango and coconut cream',
        price: 9.00,
        category: 'Desserts & Drinks',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 5,
      },
      {
        id: 'item_16',
        tenantId: 'tenant_siam_001',
        name: 'Coconut Ice Cream',
        description: 'Homemade coconut ice cream with palm sugar syrup',
        price: 8.00,
        category: 'Desserts & Drinks',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 3,
      },
      {
        id: 'item_13',
        tenantId: 'tenant_siam_001',
        name: 'Thai Iced Tea',
        description: 'Classic Thai black tea with condensed milk and ice',
        price: 5.00,
        category: 'Desserts & Drinks',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 3,
      },
      {
        id: 'item_21',
        tenantId: 'tenant_siam_001',
        name: 'Thai Green Tea',
        description: 'Iced Thai green tea with sweetened condensed milk',
        price: 5.00,
        category: 'Desserts & Drinks',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 3,
      },
      {
        id: 'item_22',
        tenantId: 'tenant_siam_001',
        name: 'Coconut Pandan Cake',
        description: 'Steamed pandan cake with coconut cream and sesame',
        price: 7.00,
        category: 'Desserts & Drinks',
        imageUrl: '',
        isAvailable: true,
        preparationTime: 5,
      },
    ],
  },
];

export const mockSalesSummary: SalesSummary = {
  totalRevenue: 1250.00,
  totalOrders: 28,
  averageOrderValue: 44.64,
  period: 'today',
  trend: {
    revenue: 12,
    orders: 5,
  },
};

export const mockSalesSummaryWeek: SalesSummary = {
  totalRevenue: 7850.00,
  totalOrders: 156,
  averageOrderValue: 50.32,
  period: 'week',
  trend: {
    revenue: 8,
    orders: 12,
  },
};

export const mockSalesSummaryMonth: SalesSummary = {
  totalRevenue: 32400.00,
  totalOrders: 680,
  averageOrderValue: 47.65,
  period: 'month',
  trend: {
    revenue: 15,
    orders: 45,
  },
};

export const mockPopularItems: PopularItem[] = [
  { itemId: 'item_1', itemName: 'Pad Thai', quantitySold: 45, revenue: 697.50 },
  { itemId: 'item_13', itemName: 'Thai Iced Tea', quantitySold: 42, revenue: 210.00 },
  { itemId: 'item_11', itemName: 'Green Curry', quantitySold: 38, revenue: 684.00 },
  { itemId: 'item_10', itemName: 'Tom Yum Soup', quantitySold: 32, revenue: 512.00 },
  { itemId: 'item_12', itemName: 'Massaman Curry', quantitySold: 28, revenue: 532.00 },
  { itemId: 'item_8', itemName: 'Mango Sticky Rice', quantitySold: 25, revenue: 225.00 },
  { itemId: 'item_14', itemName: 'Red Curry', quantitySold: 22, revenue: 396.00 },
  { itemId: 'item_2', itemName: 'Satay Chicken', quantitySold: 20, revenue: 240.00 },
  { itemId: 'item_15', itemName: 'Papaya Salad', quantitySold: 18, revenue: 252.00 },
  { itemId: 'item_18', itemName: 'Pad See Ew', quantitySold: 15, revenue: 225.00 },
];

export const mockRevenueChartData = [
  { label: 'Mon', value: 980 },
  { label: 'Tue', value: 1120 },
  { label: 'Wed', value: 890 },
  { label: 'Thu', value: 1340 },
  { label: 'Fri', value: 1560 },
  { label: 'Sat', value: 1890 },
  { label: 'Sun', value: 1680 },
];